# Generated by Django 4.1.1 on 2022-12-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DadosSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField(auto_now=True)),
                ('link', models.CharField(max_length=250)),
                ('tipo_vulnerabilidade', models.CharField(choices=[('1', 'DADOS SENSIVEIS'), ('2', 'XSS'), ('3', 'SQL INJECTOR')], max_length=2, verbose_name='Vulnerabilidade')),
                ('url_primary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISecurityA.search')),
            ],
        ),
    ]
