# Generated by Django 4.1.1 on 2022-12-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISecurityA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensiveis',
            name='tipo_vulnerabilidade',
            field=models.CharField(choices=[('1', 'DADOS SENSIVEIS'), ('2', 'XSS'), ('3', 'SQL INJECTOR')], max_length=20, verbose_name='Vulnerabilidade'),
        ),
    ]
