# Generated by Django 4.1.1 on 2022-12-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISecurityA', '0003_alter_dadossensiveis_tipo_vulnerabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensiveis',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
