# Generated by Django 4.1.1 on 2022-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISecurityA', '0004_alter_dadossensiveis_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadossensiveis',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
